#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nim
Version  : 0.19.6
Release  : 1
URL      : https://nim-lang.org/download/nim-0.19.6.tar.xz
Source0  : https://nim-lang.org/download/nim-0.19.6.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause MIT
Requires: nim-bin = %{version}-%{release}
Requires: nim-license = %{version}-%{release}
Patch1: 0001-add-build.mk.patch

%description
This package contains the Nim compiler, Nim's stdlib, tools and
documentation.
Nim is a compiled, garbage-collected systems programming language which has
an excellent productivity/performance ratio. Nim's design focuses on
efficiency, expressiveness, elegance (in the order of priority).

%package bin
Summary: bin components for the nim package.
Group: Binaries
Requires: nim-license = %{version}-%{release}

%description bin
bin components for the nim package.


%package license
Summary: license components for the nim package.
Group: Default

%description license
license components for the nim package.


%prep
%setup -q -n nim-0.19.6
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1559591260
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags} -f build.mk


%install
export SOURCE_DATE_EPOCH=1559591260
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/nim
cp copying.txt %{buildroot}/usr/share/package-licenses/nim/copying.txt
cp dist/nimble/license.txt %{buildroot}/usr/share/package-licenses/nim/dist_nimble_license.txt
cp lib/wrappers/linenoise/LICENSE.txt %{buildroot}/usr/share/package-licenses/nim/lib_wrappers_linenoise_LICENSE.txt
make -f build.mk install DESTDIR=%{buildroot}

%files
%defattr(-,root,root,-)
/usr/lib/nim/arch/x86/amd64.S
/usr/lib/nim/arch/x86/i386.S
/usr/lib/nim/core/allocators.nim
/usr/lib/nim/core/locks.nim
/usr/lib/nim/core/macrocache.nim
/usr/lib/nim/core/macros.nim
/usr/lib/nim/core/refs.nim
/usr/lib/nim/core/rlocks.nim
/usr/lib/nim/core/seqs.nim
/usr/lib/nim/core/strs.nim
/usr/lib/nim/core/typeinfo.nim
/usr/lib/nim/core/typelayouts.nim
/usr/lib/nim/cycle.h
/usr/lib/nim/deprecated/core/unsigned.nim
/usr/lib/nim/deprecated/pure/actors.nim
/usr/lib/nim/deprecated/pure/actors.nim.cfg
/usr/lib/nim/deprecated/pure/asyncio.nim
/usr/lib/nim/deprecated/pure/ftpclient.nim
/usr/lib/nim/deprecated/pure/parseurl.nim
/usr/lib/nim/deprecated/pure/rawsockets.nim
/usr/lib/nim/deprecated/pure/sockets.nim
/usr/lib/nim/genode/alloc.nim
/usr/lib/nim/genode/env.nim
/usr/lib/nim/genode_cpp/syslocks.h
/usr/lib/nim/genode_cpp/threads.h
/usr/lib/nim/impure/db_mysql.nim
/usr/lib/nim/impure/db_odbc.nim
/usr/lib/nim/impure/db_postgres.nim
/usr/lib/nim/impure/db_sqlite.nim
/usr/lib/nim/impure/nre.nim
/usr/lib/nim/impure/nre/private/util.nim
/usr/lib/nim/impure/osinfo_posix.nim
/usr/lib/nim/impure/osinfo_win.nim
/usr/lib/nim/impure/rdstdin.nim
/usr/lib/nim/impure/re.nim
/usr/lib/nim/impure/ssl.nim
/usr/lib/nim/js/asyncjs.nim
/usr/lib/nim/js/dom.nim
/usr/lib/nim/js/jsconsole.nim
/usr/lib/nim/js/jscore.nim
/usr/lib/nim/js/jsffi.nim
/usr/lib/nim/nimbase.h
/usr/lib/nim/nimrtl.nim
/usr/lib/nim/nimrtl.nim.cfg
/usr/lib/nim/nintendoswitch/switch_memory.nim
/usr/lib/nim/packages/docutils/docutils.nimble
/usr/lib/nim/packages/docutils/highlite.nim
/usr/lib/nim/packages/docutils/rst.nim
/usr/lib/nim/packages/docutils/rstast.nim
/usr/lib/nim/packages/docutils/rstgen.nim
/usr/lib/nim/packages/fsmonitor.nim
/usr/lib/nim/posix/epoll.nim
/usr/lib/nim/posix/inotify.nim
/usr/lib/nim/posix/kqueue.nim
/usr/lib/nim/posix/linux.nim
/usr/lib/nim/posix/posix.nim
/usr/lib/nim/posix/posix_linux_amd64.nim
/usr/lib/nim/posix/posix_linux_amd64_consts.nim
/usr/lib/nim/posix/posix_nintendoswitch.nim
/usr/lib/nim/posix/posix_nintendoswitch_consts.nim
/usr/lib/nim/posix/posix_other.nim
/usr/lib/nim/posix/posix_other_consts.nim
/usr/lib/nim/posix/termios.nim
/usr/lib/nim/prelude.nim
/usr/lib/nim/pure/algorithm.nim
/usr/lib/nim/pure/async.nim
/usr/lib/nim/pure/asyncdispatch.nim
/usr/lib/nim/pure/asyncdispatch.nim.cfg
/usr/lib/nim/pure/asyncfile.nim
/usr/lib/nim/pure/asyncftpclient.nim
/usr/lib/nim/pure/asyncfutures.nim
/usr/lib/nim/pure/asynchttpserver.nim
/usr/lib/nim/pure/asyncmacro.nim
/usr/lib/nim/pure/asyncnet.nim
/usr/lib/nim/pure/asyncstreams.nim
/usr/lib/nim/pure/base64.nim
/usr/lib/nim/pure/bitops.nim
/usr/lib/nim/pure/browsers.nim
/usr/lib/nim/pure/cgi.nim
/usr/lib/nim/pure/collections/LockFreeHash.nim
/usr/lib/nim/pure/collections/chains.nim
/usr/lib/nim/pure/collections/critbits.nim
/usr/lib/nim/pure/collections/deques.nim
/usr/lib/nim/pure/collections/heapqueue.nim
/usr/lib/nim/pure/collections/intsets.nim
/usr/lib/nim/pure/collections/lists.nim
/usr/lib/nim/pure/collections/queues.nim
/usr/lib/nim/pure/collections/rtarrays.nim
/usr/lib/nim/pure/collections/sequtils.nim
/usr/lib/nim/pure/collections/sets.nim
/usr/lib/nim/pure/collections/sharedlist.nim
/usr/lib/nim/pure/collections/sharedstrings.nim
/usr/lib/nim/pure/collections/sharedtables.nim
/usr/lib/nim/pure/collections/tableimpl.nim
/usr/lib/nim/pure/collections/tables.nim
/usr/lib/nim/pure/colors.nim
/usr/lib/nim/pure/complex.nim
/usr/lib/nim/pure/concurrency/cpuinfo.nim
/usr/lib/nim/pure/concurrency/cpuload.nim
/usr/lib/nim/pure/concurrency/threadpool.nim
/usr/lib/nim/pure/concurrency/threadpool.nim.cfg
/usr/lib/nim/pure/cookies.nim
/usr/lib/nim/pure/coro.nim
/usr/lib/nim/pure/coro.nimcfg
/usr/lib/nim/pure/cstrutils.nim
/usr/lib/nim/pure/db_common.nim
/usr/lib/nim/pure/distros.nim
/usr/lib/nim/pure/dynlib.nim
/usr/lib/nim/pure/editdistance.nim
/usr/lib/nim/pure/encodings.nim
/usr/lib/nim/pure/endians.nim
/usr/lib/nim/pure/events.nim
/usr/lib/nim/pure/fenv.nim
/usr/lib/nim/pure/future.nim
/usr/lib/nim/pure/hashes.nim
/usr/lib/nim/pure/htmlgen.nim
/usr/lib/nim/pure/htmlparser.nim
/usr/lib/nim/pure/httpclient.nim
/usr/lib/nim/pure/httpcore.nim
/usr/lib/nim/pure/httpserver.nim
/usr/lib/nim/pure/includes/asynccommon.nim
/usr/lib/nim/pure/includes/osenv.nim
/usr/lib/nim/pure/includes/oserr.nim
/usr/lib/nim/pure/ioselects/ioselectors_epoll.nim
/usr/lib/nim/pure/ioselects/ioselectors_kqueue.nim
/usr/lib/nim/pure/ioselects/ioselectors_poll.nim
/usr/lib/nim/pure/ioselects/ioselectors_select.nim
/usr/lib/nim/pure/json.nim
/usr/lib/nim/pure/lenientops.nim
/usr/lib/nim/pure/lexbase.nim
/usr/lib/nim/pure/logging.nim
/usr/lib/nim/pure/marshal.nim
/usr/lib/nim/pure/matchers.nim
/usr/lib/nim/pure/math.nim
/usr/lib/nim/pure/md5.nim
/usr/lib/nim/pure/memfiles.nim
/usr/lib/nim/pure/mersenne.nim
/usr/lib/nim/pure/mimetypes.nim
/usr/lib/nim/pure/nativesockets.nim
/usr/lib/nim/pure/net.nim
/usr/lib/nim/pure/nimprof.nim
/usr/lib/nim/pure/nimprof.nim.cfg
/usr/lib/nim/pure/nimtracker.nim
/usr/lib/nim/pure/oids.nim
/usr/lib/nim/pure/options.nim
/usr/lib/nim/pure/os.nim
/usr/lib/nim/pure/ospaths.nim
/usr/lib/nim/pure/osproc.nim
/usr/lib/nim/pure/oswalkdir.nim
/usr/lib/nim/pure/parsecfg.nim
/usr/lib/nim/pure/parsecsv.nim
/usr/lib/nim/pure/parsejson.nim
/usr/lib/nim/pure/parseopt.nim
/usr/lib/nim/pure/parseopt2.nim
/usr/lib/nim/pure/parsesql.nim
/usr/lib/nim/pure/parseutils.nim
/usr/lib/nim/pure/parsexml.nim
/usr/lib/nim/pure/pegs.nim
/usr/lib/nim/pure/punycode.nim
/usr/lib/nim/pure/random.nim
/usr/lib/nim/pure/rationals.nim
/usr/lib/nim/pure/ropes.nim
/usr/lib/nim/pure/scgi.nim
/usr/lib/nim/pure/securehash.nim
/usr/lib/nim/pure/segfaults.nim
/usr/lib/nim/pure/selectors.nim
/usr/lib/nim/pure/smtp.nim
/usr/lib/nim/pure/smtp.nim.cfg
/usr/lib/nim/pure/stats.nim
/usr/lib/nim/pure/streams.nim
/usr/lib/nim/pure/strformat.nim
/usr/lib/nim/pure/strmisc.nim
/usr/lib/nim/pure/strscans.nim
/usr/lib/nim/pure/strtabs.nim
/usr/lib/nim/pure/strutils.nim
/usr/lib/nim/pure/subexes.nim
/usr/lib/nim/pure/sugar.nim
/usr/lib/nim/pure/terminal.nim
/usr/lib/nim/pure/times.nim
/usr/lib/nim/pure/typetraits.nim
/usr/lib/nim/pure/unicode.nim
/usr/lib/nim/pure/unidecode/gen.py
/usr/lib/nim/pure/unidecode/unidecode.dat
/usr/lib/nim/pure/unidecode/unidecode.nim
/usr/lib/nim/pure/unittest.nim
/usr/lib/nim/pure/uri.nim
/usr/lib/nim/pure/volatile.nim
/usr/lib/nim/pure/xmldom.nim
/usr/lib/nim/pure/xmldomparser.nim
/usr/lib/nim/pure/xmlparser.nim
/usr/lib/nim/pure/xmltree.nim
/usr/lib/nim/std/sha1.nim
/usr/lib/nim/std/varints.nim
/usr/lib/nim/stdlib.nimble
/usr/lib/nim/system.nim
/usr/lib/nim/system/alloc.nim
/usr/lib/nim/system/ansi_c.nim
/usr/lib/nim/system/arithm.nim
/usr/lib/nim/system/assign.nim
/usr/lib/nim/system/atomics.nim
/usr/lib/nim/system/avltree.nim
/usr/lib/nim/system/cellsets.nim
/usr/lib/nim/system/cgprocs.nim
/usr/lib/nim/system/channels.nim
/usr/lib/nim/system/chcks.nim
/usr/lib/nim/system/debugger.nim
/usr/lib/nim/system/deepcopy.nim
/usr/lib/nim/system/dyncalls.nim
/usr/lib/nim/system/embedded.nim
/usr/lib/nim/system/endb.nim
/usr/lib/nim/system/excpt.nim
/usr/lib/nim/system/gc.nim
/usr/lib/nim/system/gc2.nim
/usr/lib/nim/system/gc_common.nim
/usr/lib/nim/system/gc_ms.nim
/usr/lib/nim/system/gc_regions.nim
/usr/lib/nim/system/helpers.nim
/usr/lib/nim/system/hti.nim
/usr/lib/nim/system/inclrtl.nim
/usr/lib/nim/system/jssys.nim
/usr/lib/nim/system/memory.nim
/usr/lib/nim/system/memtracker.nim
/usr/lib/nim/system/mmdisp.nim
/usr/lib/nim/system/nimscript.nim
/usr/lib/nim/system/osalloc.nim
/usr/lib/nim/system/platforms.nim
/usr/lib/nim/system/profiler.nim
/usr/lib/nim/system/repr.nim
/usr/lib/nim/system/reprjs.nim
/usr/lib/nim/system/sets.nim
/usr/lib/nim/system/strmantle.nim
/usr/lib/nim/system/sysio.nim
/usr/lib/nim/system/syslocks.nim
/usr/lib/nim/system/sysspawn.nim
/usr/lib/nim/system/sysstr.nim
/usr/lib/nim/system/threads.nim
/usr/lib/nim/system/timers.nim
/usr/lib/nim/system/widestrs.nim
/usr/lib/nim/windows/registry.nim
/usr/lib/nim/windows/winlean.nim
/usr/lib/nim/wrappers/iup.nim
/usr/lib/nim/wrappers/linenoise/LICENSE.txt
/usr/lib/nim/wrappers/linenoise/README.markdown
/usr/lib/nim/wrappers/linenoise/linenoise.c
/usr/lib/nim/wrappers/linenoise/linenoise.h
/usr/lib/nim/wrappers/linenoise/linenoise.nim
/usr/lib/nim/wrappers/mysql.nim
/usr/lib/nim/wrappers/odbcsql.nim
/usr/lib/nim/wrappers/openssl.nim
/usr/lib/nim/wrappers/pcre.nim
/usr/lib/nim/wrappers/postgres.nim
/usr/lib/nim/wrappers/sqlite3.nim
/usr/lib/nim/wrappers/tinyc.nim

%files bin
%defattr(-,root,root,-)
/usr/bin/nim
/usr/bin/nimble
/usr/bin/nimgrep
/usr/bin/nimsuggest

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/nim/copying.txt
/usr/share/package-licenses/nim/dist_nimble_license.txt
/usr/share/package-licenses/nim/lib_wrappers_linenoise_LICENSE.txt
