#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nim
Version  : 1.2.6
Release  : 4
URL      : https://nim-lang.org/download/nim-1.2.6.tar.xz
Source0  : https://nim-lang.org/download/nim-1.2.6.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause MIT
Requires: nim-bin = %{version}-%{release}
Requires: nim-data = %{version}-%{release}
Requires: nim-license = %{version}-%{release}
Patch1: 0001-add-build.mk.patch
Patch2: 0002-Attempt-to-make-nim-parse-a-system-wide-fallback-con.patch

%description
# Linenoise
A minimal, zero-config, BSD licensed, readline replacement used in Redis,
MongoDB, and Android.

%package bin
Summary: bin components for the nim package.
Group: Binaries
Requires: nim-data = %{version}-%{release}
Requires: nim-license = %{version}-%{release}

%description bin
bin components for the nim package.


%package data
Summary: data components for the nim package.
Group: Data

%description data
data components for the nim package.


%package license
Summary: license components for the nim package.
Group: Default

%description license
license components for the nim package.


%prep
%setup -q -n nim-1.2.6
cd %{_builddir}/nim-1.2.6
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1601916387
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}  -f build.mk


%install
export SOURCE_DATE_EPOCH=1601916387
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/nim
cp %{_builddir}/nim-1.2.6/copying.txt %{buildroot}/usr/share/package-licenses/nim/541e8c63af74be0e66873b8beb26bdf8118a31f5
cp %{_builddir}/nim-1.2.6/dist/nimble/license.txt %{buildroot}/usr/share/package-licenses/nim/22ff85e051d41d7e1171a0c0080bb51df080f326
cp %{_builddir}/nim-1.2.6/lib/wrappers/linenoise/LICENSE.txt %{buildroot}/usr/share/package-licenses/nim/3bd655bcdbe6f4f14e9da385f1953c50dd89ea8e
make -f build.mk install DESTDIR=%{buildroot}
## install_append content
mkdir -p %{buildroot}/usr/share/defaults/nim
install config/nim.cfg %{buildroot}/usr/share/defaults/nim/
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib/nim/arch/x86/amd64.S
/usr/lib/nim/arch/x86/i386.S
/usr/lib/nim/core/hotcodereloading.nim
/usr/lib/nim/core/locks.nim
/usr/lib/nim/core/macrocache.nim
/usr/lib/nim/core/macros.nim
/usr/lib/nim/core/rlocks.nim
/usr/lib/nim/core/typeinfo.nim
/usr/lib/nim/cycle.h
/usr/lib/nim/deprecated/pure/LockFreeHash.nim
/usr/lib/nim/deprecated/pure/events.nim
/usr/lib/nim/deprecated/pure/ospaths.nim
/usr/lib/nim/deprecated/pure/parseopt2.nim
/usr/lib/nim/deprecated/pure/securehash.nim
/usr/lib/nim/deprecated/pure/sharedstrings.nim
/usr/lib/nim/experimental/diff.nim
/usr/lib/nim/genode/alloc.nim
/usr/lib/nim/genode/env.nim
/usr/lib/nim/genode_cpp/syslocks.h
/usr/lib/nim/genode_cpp/threads.h
/usr/lib/nim/impure/db_mysql.nim
/usr/lib/nim/impure/db_odbc.nim
/usr/lib/nim/impure/db_postgres.nim
/usr/lib/nim/impure/db_sqlite.nim
/usr/lib/nim/impure/nre.nim
/usr/lib/nim/impure/nre/private/util.nim
/usr/lib/nim/impure/rdstdin.nim
/usr/lib/nim/impure/re.nim
/usr/lib/nim/js/asyncjs.nim
/usr/lib/nim/js/dom.nim
/usr/lib/nim/js/jsconsole.nim
/usr/lib/nim/js/jscore.nim
/usr/lib/nim/js/jsffi.nim
/usr/lib/nim/nimbase.h
/usr/lib/nim/nimhcr.nim
/usr/lib/nim/nimhcr.nim.cfg
/usr/lib/nim/nimrtl.nim
/usr/lib/nim/nimrtl.nim.cfg
/usr/lib/nim/nintendoswitch/switch_memory.nim
/usr/lib/nim/packages/docutils/docutils.nimble
/usr/lib/nim/packages/docutils/highlite.nim
/usr/lib/nim/packages/docutils/rst.nim
/usr/lib/nim/packages/docutils/rstast.nim
/usr/lib/nim/packages/docutils/rstgen.nim
/usr/lib/nim/posix/epoll.nim
/usr/lib/nim/posix/inotify.nim
/usr/lib/nim/posix/kqueue.nim
/usr/lib/nim/posix/linux.nim
/usr/lib/nim/posix/posix.nim
/usr/lib/nim/posix/posix_linux_amd64.nim
/usr/lib/nim/posix/posix_linux_amd64_consts.nim
/usr/lib/nim/posix/posix_macos_amd64.nim
/usr/lib/nim/posix/posix_nintendoswitch.nim
/usr/lib/nim/posix/posix_nintendoswitch_consts.nim
/usr/lib/nim/posix/posix_openbsd_amd64.nim
/usr/lib/nim/posix/posix_other.nim
/usr/lib/nim/posix/posix_other_consts.nim
/usr/lib/nim/posix/posix_utils.nim
/usr/lib/nim/posix/termios.nim
/usr/lib/nim/prelude.nim
/usr/lib/nim/pure/algorithm.nim
/usr/lib/nim/pure/async.nim
/usr/lib/nim/pure/asyncdispatch.nim
/usr/lib/nim/pure/asyncdispatch.nim.cfg
/usr/lib/nim/pure/asyncfile.nim
/usr/lib/nim/pure/asyncftpclient.nim
/usr/lib/nim/pure/asyncfutures.nim
/usr/lib/nim/pure/asynchttpserver.nim
/usr/lib/nim/pure/asyncmacro.nim
/usr/lib/nim/pure/asyncnet.nim
/usr/lib/nim/pure/asyncstreams.nim
/usr/lib/nim/pure/base64.nim
/usr/lib/nim/pure/bitops.nim
/usr/lib/nim/pure/browsers.nim
/usr/lib/nim/pure/cgi.nim
/usr/lib/nim/pure/collections/chains.nim
/usr/lib/nim/pure/collections/critbits.nim
/usr/lib/nim/pure/collections/deques.nim
/usr/lib/nim/pure/collections/hashcommon.nim
/usr/lib/nim/pure/collections/heapqueue.nim
/usr/lib/nim/pure/collections/intsets.nim
/usr/lib/nim/pure/collections/lists.nim
/usr/lib/nim/pure/collections/rtarrays.nim
/usr/lib/nim/pure/collections/sequtils.nim
/usr/lib/nim/pure/collections/setimpl.nim
/usr/lib/nim/pure/collections/sets.nim
/usr/lib/nim/pure/collections/sharedlist.nim
/usr/lib/nim/pure/collections/sharedtables.nim
/usr/lib/nim/pure/collections/tableimpl.nim
/usr/lib/nim/pure/collections/tables.nim
/usr/lib/nim/pure/colors.nim
/usr/lib/nim/pure/complex.nim
/usr/lib/nim/pure/concurrency/atomics.nim
/usr/lib/nim/pure/concurrency/cpuinfo.nim
/usr/lib/nim/pure/concurrency/cpuload.nim
/usr/lib/nim/pure/concurrency/threadpool.nim
/usr/lib/nim/pure/concurrency/threadpool.nim.cfg
/usr/lib/nim/pure/cookies.nim
/usr/lib/nim/pure/coro.nim
/usr/lib/nim/pure/coro.nimcfg
/usr/lib/nim/pure/cstrutils.nim
/usr/lib/nim/pure/db_common.nim
/usr/lib/nim/pure/distros.nim
/usr/lib/nim/pure/dynlib.nim
/usr/lib/nim/pure/encodings.nim
/usr/lib/nim/pure/endians.nim
/usr/lib/nim/pure/fenv.nim
/usr/lib/nim/pure/future.nim
/usr/lib/nim/pure/hashes.nim
/usr/lib/nim/pure/htmlgen.nim
/usr/lib/nim/pure/htmlparser.nim
/usr/lib/nim/pure/httpclient.nim
/usr/lib/nim/pure/httpcore.nim
/usr/lib/nim/pure/includes/decode_helpers.nim
/usr/lib/nim/pure/includes/osenv.nim
/usr/lib/nim/pure/includes/oserr.nim
/usr/lib/nim/pure/includes/osseps.nim
/usr/lib/nim/pure/includes/unicode_ranges.nim
/usr/lib/nim/pure/ioselects/ioselectors_epoll.nim
/usr/lib/nim/pure/ioselects/ioselectors_kqueue.nim
/usr/lib/nim/pure/ioselects/ioselectors_poll.nim
/usr/lib/nim/pure/ioselects/ioselectors_select.nim
/usr/lib/nim/pure/json.nim
/usr/lib/nim/pure/lenientops.nim
/usr/lib/nim/pure/lexbase.nim
/usr/lib/nim/pure/logging.nim
/usr/lib/nim/pure/marshal.nim
/usr/lib/nim/pure/math.nim
/usr/lib/nim/pure/md5.nim
/usr/lib/nim/pure/memfiles.nim
/usr/lib/nim/pure/mersenne.nim
/usr/lib/nim/pure/mimetypes.nim
/usr/lib/nim/pure/nativesockets.nim
/usr/lib/nim/pure/net.nim
/usr/lib/nim/pure/nimprof.nim
/usr/lib/nim/pure/nimprof.nim.cfg
/usr/lib/nim/pure/nimtracker.nim
/usr/lib/nim/pure/oids.nim
/usr/lib/nim/pure/options.nim
/usr/lib/nim/pure/os.nim
/usr/lib/nim/pure/osproc.nim
/usr/lib/nim/pure/oswalkdir.nim
/usr/lib/nim/pure/parsecfg.nim
/usr/lib/nim/pure/parsecsv.nim
/usr/lib/nim/pure/parsejson.nim
/usr/lib/nim/pure/parseopt.nim
/usr/lib/nim/pure/parsesql.nim
/usr/lib/nim/pure/parseutils.nim
/usr/lib/nim/pure/parsexml.nim
/usr/lib/nim/pure/pathnorm.nim
/usr/lib/nim/pure/pegs.nim
/usr/lib/nim/pure/punycode.nim
/usr/lib/nim/pure/random.nim
/usr/lib/nim/pure/rationals.nim
/usr/lib/nim/pure/reservedmem.nim
/usr/lib/nim/pure/ropes.nim
/usr/lib/nim/pure/segfaults.nim
/usr/lib/nim/pure/selectors.nim
/usr/lib/nim/pure/smtp.nim
/usr/lib/nim/pure/smtp.nim.cfg
/usr/lib/nim/pure/ssl_certs.nim
/usr/lib/nim/pure/stats.nim
/usr/lib/nim/pure/streams.nim
/usr/lib/nim/pure/strformat.nim
/usr/lib/nim/pure/strmisc.nim
/usr/lib/nim/pure/strscans.nim
/usr/lib/nim/pure/strtabs.nim
/usr/lib/nim/pure/strutils.nim
/usr/lib/nim/pure/sugar.nim
/usr/lib/nim/pure/terminal.nim
/usr/lib/nim/pure/times.nim
/usr/lib/nim/pure/typetraits.nim
/usr/lib/nim/pure/unicode.nim
/usr/lib/nim/pure/unidecode/gen.py
/usr/lib/nim/pure/unidecode/unidecode.dat
/usr/lib/nim/pure/unidecode/unidecode.nim
/usr/lib/nim/pure/unittest.nim
/usr/lib/nim/pure/uri.nim
/usr/lib/nim/pure/volatile.nim
/usr/lib/nim/pure/xmlparser.nim
/usr/lib/nim/pure/xmltree.nim
/usr/lib/nim/std/compilesettings.nim
/usr/lib/nim/std/decls.nim
/usr/lib/nim/std/editdistance.nim
/usr/lib/nim/std/logic.nim
/usr/lib/nim/std/monotimes.nim
/usr/lib/nim/std/private/underscored_calls.nim
/usr/lib/nim/std/sha1.nim
/usr/lib/nim/std/stackframes.nim
/usr/lib/nim/std/sums.nim
/usr/lib/nim/std/time_t.nim
/usr/lib/nim/std/varints.nim
/usr/lib/nim/std/with.nim
/usr/lib/nim/std/wordwrap.nim
/usr/lib/nim/std/wrapnils.nim
/usr/lib/nim/stdlib.nimble
/usr/lib/nim/system.nim
/usr/lib/nim/system/alloc.nim
/usr/lib/nim/system/ansi_c.nim
/usr/lib/nim/system/arithm.nim
/usr/lib/nim/system/arithmetics.nim
/usr/lib/nim/system/assertions.nim
/usr/lib/nim/system/assign.nim
/usr/lib/nim/system/atomics.nim
/usr/lib/nim/system/avltree.nim
/usr/lib/nim/system/basic_types.nim
/usr/lib/nim/system/cellsets.nim
/usr/lib/nim/system/cgprocs.nim
/usr/lib/nim/system/channels.nim
/usr/lib/nim/system/chcks.nim
/usr/lib/nim/system/comparisons.nim
/usr/lib/nim/system/cyclebreaker.nim
/usr/lib/nim/system/cyclicrefs_v2.nim
/usr/lib/nim/system/deepcopy.nim
/usr/lib/nim/system/dollars.nim
/usr/lib/nim/system/dyncalls.nim
/usr/lib/nim/system/embedded.nim
/usr/lib/nim/system/exceptions.nim
/usr/lib/nim/system/excpt.nim
/usr/lib/nim/system/fatal.nim
/usr/lib/nim/system/formatfloat.nim
/usr/lib/nim/system/gc.nim
/usr/lib/nim/system/gc2.nim
/usr/lib/nim/system/gc_common.nim
/usr/lib/nim/system/gc_hooks.nim
/usr/lib/nim/system/gc_interface.nim
/usr/lib/nim/system/gc_ms.nim
/usr/lib/nim/system/gc_regions.nim
/usr/lib/nim/system/hti.nim
/usr/lib/nim/system/inclrtl.nim
/usr/lib/nim/system/indexerrors.nim
/usr/lib/nim/system/integerops.nim
/usr/lib/nim/system/io.nim
/usr/lib/nim/system/iterators.nim
/usr/lib/nim/system/iterators_1.nim
/usr/lib/nim/system/jssys.nim
/usr/lib/nim/system/memalloc.nim
/usr/lib/nim/system/memory.nim
/usr/lib/nim/system/memtracker.nim
/usr/lib/nim/system/mm/boehm.nim
/usr/lib/nim/system/mm/go.nim
/usr/lib/nim/system/mm/malloc.nim
/usr/lib/nim/system/mm/none.nim
/usr/lib/nim/system/mmdisp.nim
/usr/lib/nim/system/nimscript.nim
/usr/lib/nim/system/osalloc.nim
/usr/lib/nim/system/platforms.nim
/usr/lib/nim/system/profiler.nim
/usr/lib/nim/system/refs_v2.nim
/usr/lib/nim/system/repr.nim
/usr/lib/nim/system/repr_v2.nim
/usr/lib/nim/system/reprjs.nim
/usr/lib/nim/system/seqs_v2.nim
/usr/lib/nim/system/setops.nim
/usr/lib/nim/system/sets.nim
/usr/lib/nim/system/strmantle.nim
/usr/lib/nim/system/strs_v2.nim
/usr/lib/nim/system/syslocks.nim
/usr/lib/nim/system/sysspawn.nim
/usr/lib/nim/system/sysstr.nim
/usr/lib/nim/system/threadlocalstorage.nim
/usr/lib/nim/system/threads.nim
/usr/lib/nim/system/timers.nim
/usr/lib/nim/system/widestrs.nim
/usr/lib/nim/system_overview.rst
/usr/lib/nim/windows/registry.nim
/usr/lib/nim/windows/winlean.nim
/usr/lib/nim/wrappers/iup.nim
/usr/lib/nim/wrappers/linenoise/LICENSE.txt
/usr/lib/nim/wrappers/linenoise/README.markdown
/usr/lib/nim/wrappers/linenoise/linenoise.c
/usr/lib/nim/wrappers/linenoise/linenoise.h
/usr/lib/nim/wrappers/linenoise/linenoise.nim
/usr/lib/nim/wrappers/mysql.nim
/usr/lib/nim/wrappers/odbcsql.nim
/usr/lib/nim/wrappers/openssl.nim
/usr/lib/nim/wrappers/pcre.nim
/usr/lib/nim/wrappers/postgres.nim
/usr/lib/nim/wrappers/sqlite3.nim
/usr/lib/nim/wrappers/tinyc.nim

%files bin
%defattr(-,root,root,-)
/usr/bin/nim
/usr/bin/nimble
/usr/bin/nimgrep
/usr/bin/nimsuggest

%files data
%defattr(-,root,root,-)
/usr/share/defaults/nim/nim.cfg

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/nim/22ff85e051d41d7e1171a0c0080bb51df080f326
/usr/share/package-licenses/nim/3bd655bcdbe6f4f14e9da385f1953c50dd89ea8e
/usr/share/package-licenses/nim/541e8c63af74be0e66873b8beb26bdf8118a31f5
